# Generated by Django 5.2.6 on 2025-09-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Nueva', 'Nueva'), ('Usada', 'Usada'), ('Averiada', 'Averiada')], default='Nueva', max_length=50)),
            ],
        ),
    ]
