# Generated by Django 5.2.6 on 2025-09-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otro_negocio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='pago_completo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
