# Generated by Django 5.2.6 on 2025-09-11 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otro_negocio', '0002_transaccion_pago_completo_alter_cuenta_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Cliente', 'Cliente'), ('Proveedor', 'Proveedor')], max_length=50)),
                ('contacto', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='deuda',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otro_negocio.persona'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='otro_negocio.persona'),
        ),
    ]
