# Generated by Django 5.2.6 on 2025-09-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_herramienta_proveedor_compra_venta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Herramienta',
        ),
    ]
