# Generated by Django 5.2.6 on 2025-09-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_marca_remove_valoratributo_atributo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variacionproducto',
            name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='variacionproducto',
            name='stock',
        ),
        migrations.AddField(
            model_name='imagenproducto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='producto',
            name='condicion',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Averiado', 'Averiado')], default='Nuevo', max_length=50),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Vendido', 'Vendido'), ('Reservado', 'Reservado')], default='Disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
