# Generated by Django 5.2.6 on 2025-09-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_remove_variacionproducto_precio_venta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
