# Generated by Django 5.2.6 on 2025-09-12 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_remove_producto_precio_venta_remove_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej. 'Talla', 'Color', 'Material'", max_length=100, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='variacionproducto',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='variacionproducto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='variacionproducto',
            name='sku',
            field=models.CharField(blank=True, help_text='SKU de la variación', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='variacionproducto',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ValorAtributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(help_text="Ej. 'M', 'Azul', 'Algodón'", max_length=100)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.atributo')),
            ],
            options={
                'unique_together': {('atributo', 'valor')},
            },
        ),
        migrations.AddField(
            model_name='variacionproducto',
            name='atributos',
            field=models.ManyToManyField(to='productos.valoratributo'),
        ),
        migrations.RemoveField(
            model_name='variacionproducto',
            name='nombre',
        ),
    ]
