# Generated by Django 5.2.6 on 2025-09-17 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_subcategoria_producto_subcategoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidasProducto',
            fields=[
                ('variacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='medidas', serialize=False, to='productos.variacionproducto')),
                ('peso_gramos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('alto_cm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ancho_cm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profundidad_cm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
